version: '3.4'

services:
  api:
    build: 
      context: ./back_end
      target: dev
    stdin_open: true
    tty: true
    ports:
      - 1998:1998
    volumes:
      - ./back_end/go.mod:/app/go.mod
      - ./back_end/server.go:/app/server.go
      - ./back_end/api/:/app/api
