version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: ./back_end/docker/Dockerfile
      target: builder
    command: ["/go/bin/air", "-c", "/go/src/.air.toml"]
    ports:
      - 1998:1998
    volumes:
      - ./back_end/go.mod:/go/src/go.mod
      - ./back_end/go.sum:/go/src/go.sum
      - ./back_end/server.go:/go/src/server.go
      - ./back_end/credentials.json:/go/src/credentials.json
      - ./back_end/.air.toml:/go/src/.air.toml
      - ./back_end/api/:/go/src/api
  ui:
    image: node:13.8.0
    stdin_open: true
    tty: true
    ports:
      - 1997:1997
    volumes:
      - ./front_end/ui/:/usr/src/ui
    working_dir: /usr/src/ui
    command: sh -c "PORT=1997 yarn start"