version: '3.4'

services:
  api:
    build: 
      context: ./back_end
      target: dev
    stdin_open: true
    tty: true
    ports:
      - 1998:1998
    volumes:
      - ./back_end/go.mod:/app/go.mod
      - ./back_end/server.go:/app/server.go
      - ./back_end/api/:/app/api
  ui:
    image: node:13.8.0
    stdin_open: true
    tty: true
    ports:
      - 1997:1997
    volumes: 
      - ./front_end/ui/:/usr/src/ui
    working_dir: /usr/src/ui
    command: sh -c "PORT=1997 yarn start"